syntax on
set hls
set number
set wildmenu
set wildmode=full
set backspace=indent,eol,start
set history=200
set timeoutlen=1000 ttimeoutlen=0

let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
